name: Sample SSH server workflow

on:
  workflow_dispatch:
  
jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Start SSH server on failure
      #if: ${{ failure() }}
      timeout-minutes: 10
      uses: ./
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ github.event.inputs.sshPublicKey }}"